apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountgrpc
  labels:
    app: discountgrpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountgrpc
  template:
    metadata:
      labels:
        app: discountgrpc
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "discountgrpc"        
        dapr.io/app-port: "5007"        
        dapr.io/config: "config"        
        dapr.io/app-protocol: "grpc"        
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: discountgrpc
        image: siddocker29/globoticket.services.discount:latest
        ports:
        - containerPort: 5007        
        resources:
          limits:
            cpu: "0.15"
        imagePullPolicy: Always
        env:               
        - name: ConnectionStrings__DefaultConnection          
          valueFrom: 
            secretKeyRef:
              name: discount-db
              key: connectionstring                                          