apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingbasket
  labels:
    app: shoppingbasket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingbasket
  template:
    metadata:
      labels:
        app: shoppingbasket
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "shoppingbasket"
        dapr.io/app-port: "80"
        dapr.io/config: "config"
        dapr.io/sidecar-listen-addresses: "0.0.0.0"        
        dapr.io/sidecar-liveness-probe-delay-seconds: "6"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: shoppingbasket
        image: siddocker29/globoticket.services.shoppingbasket:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.15"
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: ConnectionStrings__DefaultConnection          
          valueFrom: 
            secretKeyRef:
              name: shoppingbasket-db
              key: connectionstring